Function Get-ADComputer {
	[CmdletBinding(
		DefaultParametersetname="Filter",
		SupportsShouldProcess=$true,
		ConfirmImpact='Medium'
	)]
	Param(
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
			[ValidateSet('Negotiate','Basic')]
				$AuthType,
		[Parameter(
			Mandatory=$False
			#,ParameterSetName='Explicit'
		)]
				$Credential,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='Filter'
		)]
				$Filter,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='Identity'
		)]
				$Identity,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='LDAPFilter'
		)]
				$LDAPFilter,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='Identity'
		)]
				$Partition,
		[Parameter(
			Mandatory=$False
			#,ParameterSetName='Explicit'
		)]
				$Properties,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
				$ResultPageSize,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
				$ResultSetSize,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
				$SearchBase,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
				$SearchScope,
		[Parameter(
			Mandatory=$False
			#,ParameterSetName='Explicit'
		)]
				$Server
	)
	$a = [system.directoryservices.directorysearcher]::new()
	$a
	$PSCmdlet.ParameterSetName
}