Function Get-ADUser {
	[CmdletBinding(
		DefaultParametersetname="Filter",
		SupportsShouldProcess=$true,
		ConfirmImpact='Medium'
	)]
	[OutputType([System.DirectoryServices.AccountManagement.UserPrincipal])]
	Param(
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
			[ValidateSet('Negotiate','Basic')]
				[System.DirectoryServices.Protocols.AuthType]$AuthType = [System.DirectoryServices.Protocols.AuthType]::Negotiate,
		[Parameter(
			Mandatory=$False
			#,ParameterSetName='Explicit'
		)]
			[ValidateNotNullOrEmpty()]
				[PSCredential]$Credential,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='Filter'
		)]
			[ValidateNotNullOrEmpty()]
				[String]$Filter,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='Identity',
			Position=1
		)]
				$Identity,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='LDAPFilter'
		)]
			[ValidateNotNullOrEmpty()]
				[String]$LDAPFilter,
		[Parameter(
			Mandatory=$False,
			ParameterSetName='Identity'
		)]
			[ValidateNotNullOrEmpty()]
				[String]$Partition,
		[Parameter(
			Mandatory=$False
			#,ParameterSetName='Explicit'
		)]
			[ValidateNotNullOrEmpty()]
				[String[]]$Properties,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
			[ValidateNotNullOrEmpty()]
				[Int32]$ResultPageSize = 256,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
				[Int32]$ResultSetSize,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
				[String]$SearchBase,
		[Parameter(
			Mandatory=$False,
			ParameterSetName=('Filter','LDAPFilter')
		)]
			[ValidateSet('Base',0,'OneLevel',1,'Subtree',2)]
				$SearchScope,
		[Parameter(
			Mandatory=$False
			#,ParameterSetName='Explicit'
		)]
				[String]$Server
	)
	$a = [system.directoryservices.directorysearcher]::new()
	$a
	$PSCmdlet.ParameterSetName
}